//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNS.ERP.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VNS.ERP.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap arrow_left {
            get {
                object obj = ResourceManager.GetObject("arrow_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_right {
            get {
                object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BangDoiChieuChuyenKho {
            get {
                object obj = ResourceManager.GetObject("BangDoiChieuChuyenKho", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap banggia_fantich {
            get {
                object obj = ResourceManager.GetObject("banggia-fantich", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BangKeXuatHang {
            get {
                object obj = ResourceManager.GetObject("BangKeXuatHang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baocao {
            get {
                object obj = ResourceManager.GetObject("baocao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baocao_bangcandoiketoan {
            get {
                object obj = ResourceManager.GetObject("baocao_bangcandoiketoan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baocao_bangcandoitaikhoan {
            get {
                object obj = ResourceManager.GetObject("baocao_bangcandoitaikhoan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baocao_bangchungtukhongcohoadon {
            get {
                object obj = ResourceManager.GetObject("baocao_bangchungtukhongcohoadon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baocao_bangchungtuvat_daura {
            get {
                object obj = ResourceManager.GetObject("baocao_bangchungtuvat_daura", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baocao_bangchungtuvat_dauvao {
            get {
                object obj = ResourceManager.GetObject("baocao_bangchungtuvat_dauvao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baocao_bangchungtuvat_dauvao1 {
            get {
                object obj = ResourceManager.GetObject("baocao_bangchungtuvat_dauvao1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baocao_ketquakinhdoanh {
            get {
                object obj = ResourceManager.GetObject("baocao_ketquakinhdoanh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baocao_kiemtrathanhpham {
            get {
                object obj = ResourceManager.GetObject("baocao_kiemtrathanhpham", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baocao_phatichngoai {
            get {
                object obj = ResourceManager.GetObject("baocao-phatichngoai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baocao_QLCL {
            get {
                object obj = ResourceManager.GetObject("baocao-QLCL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baocao_sodochu_t {
            get {
                object obj = ResourceManager.GetObject("baocao_sodochu_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baocao_tansuatkiemnglieutlo {
            get {
                object obj = ResourceManager.GetObject("baocao-tansuatkiemnglieutlo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baocao_tansuatkiemnguyelieu {
            get {
                object obj = ResourceManager.GetObject("baocao-tansuatkiemnguyelieu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baocao_tansuatkiemthanhpham {
            get {
                object obj = ResourceManager.GetObject("baocao-tansuatkiemthanhpham", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baocao_VAT {
            get {
                object obj = ResourceManager.GetObject("baocao_VAT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baocaochifi_phantich {
            get {
                object obj = ResourceManager.GetObject("baocaochifi-phantich", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baocaoPPT {
            get {
                object obj = ResourceManager.GetObject("baocaoPPT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baocaot_hop_TP {
            get {
                object obj = ResourceManager.GetObject("baocaot.hop-TP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baocaothop_kqkiemthanhpham {
            get {
                object obj = ResourceManager.GetObject("baocaothop-kqkiemthanhpham", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BH_DinhMucgChietXuat {
            get {
                object obj = ResourceManager.GetObject("BH_DinhMucgChietXuat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BH_DinhMucgCongNo {
            get {
                object obj = ResourceManager.GetObject("BH_DinhMucgCongNo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BH_DonDatHang {
            get {
                object obj = ResourceManager.GetObject("BH_DonDatHang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BH_GiaBanThanhPham {
            get {
                object obj = ResourceManager.GetObject("BH_GiaBanThanhPham", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BH_KhachHang {
            get {
                object obj = ResourceManager.GetObject("BH_KhachHang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BH_KhachHangThanhToan {
            get {
                object obj = ResourceManager.GetObject("BH_KhachHangThanhToan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BH_PhieuYeuCauBanHang {
            get {
                object obj = ResourceManager.GetObject("BH_PhieuYeuCauBanHang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BH_TonDongCongNo {
            get {
                object obj = ResourceManager.GetObject("BH_TonDongCongNo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap can_nhat_gia_thanh_pham {
            get {
                object obj = ResourceManager.GetObject("can-nhat-gia-thanh-pham", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cap_nhat_gia_nguye_lieu_san_xuat {
            get {
                object obj = ResourceManager.GetObject("cap-nhat-gia-nguye-lieu-san-xuat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cap_nhat_gia_thanh_san_pham {
            get {
                object obj = ResourceManager.GetObject("cap-nhat-gia-thanh-san-pham", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chi_nhanh {
            get {
                object obj = ResourceManager.GetObject("chi-nhanh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chi_phi_tra_truoc {
            get {
                object obj = ResourceManager.GetObject("chi-phi-tra-truoc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChiPhiSX {
            get {
                object obj = ResourceManager.GetObject("ChiPhiSX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChiTietSX {
            get {
                object obj = ResourceManager.GetObject("ChiTietSX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chitieu_kythuat {
            get {
                object obj = ResourceManager.GetObject("chitieu-kythuat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chung_tu_khac {
            get {
                object obj = ResourceManager.GetObject("chung_tu_khac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cong_cu_dung_cu {
            get {
                object obj = ResourceManager.GetObject("cong-cu-dung-cu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cong_thuc_nhan_cong {
            get {
                object obj = ResourceManager.GetObject("cong-thuc-nhan-cong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cong_thuc_NVL {
            get {
                object obj = ResourceManager.GetObject("cong-thuc-NVL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap congcudungcu {
            get {
                object obj = ResourceManager.GetObject("congcudungcu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap congcudungcu1 {
            get {
                object obj = ResourceManager.GetObject("congcudungcu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap congno {
            get {
                object obj = ResourceManager.GetObject("congno", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap congnoNam {
            get {
                object obj = ResourceManager.GetObject("congnoNam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap congnoThang {
            get {
                object obj = ResourceManager.GetObject("congnoThang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CTmuahang {
            get {
                object obj = ResourceManager.GetObject("CTmuahang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CTnoTungHD {
            get {
                object obj = ResourceManager.GetObject("CTnoTungHD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CTSoChe {
            get {
                object obj = ResourceManager.GetObject("CTSoChe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CTthutien {
            get {
                object obj = ResourceManager.GetObject("CTthutien", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CTXuatThanhPham {
            get {
                object obj = ResourceManager.GetObject("CTXuatThanhPham", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CTXuatThanhPhamBan {
            get {
                object obj = ResourceManager.GetObject("CTXuatThanhPhamBan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dah_Muc_doi_tuong {
            get {
                object obj = ResourceManager.GetObject("Dah-Muc-doi-tuong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dah_Muc_doi_tuong_khac {
            get {
                object obj = ResourceManager.GetObject("Dah-Muc-doi-tuong-khac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dah_Muc_doi_tuong_phan_loai_doi_tuong {
            get {
                object obj = ResourceManager.GetObject("Dah-Muc-doi-tuong-phan-loai-doi-tuong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dah_Muc_doi_tuong_quy_tien_mat {
            get {
                object obj = ResourceManager.GetObject("Dah-Muc-doi-tuong-quy-tien-mat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Danh_Muc {
            get {
                object obj = ResourceManager.GetObject("Danh Muc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap danh_muc_nha_cung_cap {
            get {
                object obj = ResourceManager.GetObject("danh-muc-nha-cung-cap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap danhmuc_doituong_khachhang {
            get {
                object obj = ResourceManager.GetObject("danhmuc_doituong_khachhang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap danhmuc_nghiepvumau {
            get {
                object obj = ResourceManager.GetObject("danhmuc_nghiepvumau", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap danhmuc_taikhoan {
            get {
                object obj = ResourceManager.GetObject("danhmuc_taikhoan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap danhmuc_yeuto {
            get {
                object obj = ResourceManager.GetObject("danhmuc_yeuto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap danhmuc_yeuto_danhmuc {
            get {
                object obj = ResourceManager.GetObject("danhmuc_yeuto_danhmuc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap danhmuc_yeuto_phanloai_yeuto {
            get {
                object obj = ResourceManager.GetObject("danhmuc_yeuto_phanloai_yeuto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap doi_tuong_tam_ung {
            get {
                object obj = ResourceManager.GetObject("doi-tuong-tam-ung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dong_so {
            get {
                object obj = ResourceManager.GetObject("Dong so", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap donvivanchuyen {
            get {
                object obj = ResourceManager.GetObject("donvivanchuyen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gia_thanh {
            get {
                object obj = ResourceManager.GetObject("gia-thanh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hao_mon {
            get {
                object obj = ResourceManager.GetObject("hao-mon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IIConBanHang {
            get {
                object obj = ResourceManager.GetObject("IIConBanHang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kcs {
            get {
                object obj = ResourceManager.GetObject("kcs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kehoach_kiemtranguyenlieu {
            get {
                object obj = ResourceManager.GetObject("kehoach-kiemtranguyenlieu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kehoach_kiemtrathanhpham {
            get {
                object obj = ResourceManager.GetObject("kehoach-kiemtrathanhpham", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ketchuyencuoiky {
            get {
                object obj = ResourceManager.GetObject("ketchuyencuoiky", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ketchuyendauthang {
            get {
                object obj = ResourceManager.GetObject("ketchuyendauthang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kho {
            get {
                object obj = ResourceManager.GetObject("Kho", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KHO_BAOCAO {
            get {
                object obj = ResourceManager.GetObject("KHO_BAOCAO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KHO_BAOCAO_SX_NHAPXUATTON {
            get {
                object obj = ResourceManager.GetObject("KHO_BAOCAO_SX_NHAPXUATTON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KHO_DANHMUC {
            get {
                object obj = ResourceManager.GetObject("KHO_DANHMUC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KHO_DANHMUC_kHO {
            get {
                object obj = ResourceManager.GetObject("KHO_DANHMUC_kHO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KHO_DANHMUC_MANHAPXUAT {
            get {
                object obj = ResourceManager.GetObject("KHO_DANHMUC_MANHAPXUAT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KHO_DANHMUC_NGUYENLIEU {
            get {
                object obj = ResourceManager.GetObject("KHO_DANHMUC_NGUYENLIEU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KHO_DANHMUC_THANHPHAM {
            get {
                object obj = ResourceManager.GetObject("KHO_DANHMUC_THANHPHAM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KHO_DANHMUC_XECAN {
            get {
                object obj = ResourceManager.GetObject("KHO_DANHMUC_XECAN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kho_nhaphang {
            get {
                object obj = ResourceManager.GetObject("Kho_nhaphang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KHO_PHIEU {
            get {
                object obj = ResourceManager.GetObject("KHO_PHIEU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KHO_PHIEUCAN {
            get {
                object obj = ResourceManager.GetObject("KHO_PHIEUCAN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KHO_PHIEUCAN_NHAP {
            get {
                object obj = ResourceManager.GetObject("KHO_PHIEUCAN_NHAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KHO_PHIEUCAN_XUAT {
            get {
                object obj = ResourceManager.GetObject("KHO_PHIEUCAN_XUAT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KHO_PHIEUNHAPXUAT {
            get {
                object obj = ResourceManager.GetObject("KHO_PHIEUNHAPXUAT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KHO_PHIEUNHAPXUAT_NHAP {
            get {
                object obj = ResourceManager.GetObject("KHO_PHIEUNHAPXUAT_NHAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KHO_PHIEUNHAPXUAT_XUAT {
            get {
                object obj = ResourceManager.GetObject("KHO_PHIEUNHAPXUAT_XUAT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KHO_TONDONG {
            get {
                object obj = ResourceManager.GetObject("KHO_TONDONG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KHO_XACNHAN {
            get {
                object obj = ResourceManager.GetObject("KHO_XACNHAN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kho_xuathang {
            get {
                object obj = ResourceManager.GetObject("Kho_xuathang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap khoa_so {
            get {
                object obj = ResourceManager.GetObject("khoa-so", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kiem_tra_nguyen_lieu {
            get {
                object obj = ResourceManager.GetObject("kiem-tra-nguyen-lieu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kiem_tra_thanh_pham {
            get {
                object obj = ResourceManager.GetObject("kiem-tra-thanh-pham", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kqphantich_nglieunoibo {
            get {
                object obj = ResourceManager.GetObject("kqphantich-nglieunoibo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kqphantich_thanhphamnoibo {
            get {
                object obj = ResourceManager.GetObject("kqphantich-thanhphamnoibo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kqphantichtucacttphiangoai {
            get {
                object obj = ResourceManager.GetObject("kqphantichtucacttphiangoai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loginIcon {
            get {
                object obj = ResourceManager.GetObject("loginIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loginIcon2 {
            get {
                object obj = ResourceManager.GetObject("loginIcon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logo2 {
            get {
                object obj = ResourceManager.GetObject("Logo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logo21 {
            get {
                object obj = ResourceManager.GetObject("Logo21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap luu_chuyen_tien_te {
            get {
                object obj = ResourceManager.GetObject("luu-chuyen-tien-te", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mo_So {
            get {
                object obj = ResourceManager.GetObject("Mo So", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ngan_Hang {
            get {
                object obj = ResourceManager.GetObject("Ngan Hang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nhanketqua_cactrungtamngoai {
            get {
                object obj = ResourceManager.GetObject("nhanketqua-cactrungtamngoai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nhanketqua_PPT {
            get {
                object obj = ResourceManager.GetObject("nhanketqua-PPT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nhapkho {
            get {
                object obj = ResourceManager.GetObject("nhapkho", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nhat_ky_chung {
            get {
                object obj = ResourceManager.GetObject("nhat-ky-chung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NXuatTonTheoCa {
            get {
                object obj = ResourceManager.GetObject("NXuatTonTheoCa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap people_1_ {
            get {
                object obj = ResourceManager.GetObject("people[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phanloaigiaodichnganhang {
            get {
                object obj = ResourceManager.GetObject("phanloaigiaodichnganhang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phantichmuahang {
            get {
                object obj = ResourceManager.GetObject("phantichmuahang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phieu_chi_ngan_hang {
            get {
                object obj = ResourceManager.GetObject("phieu-chi-ngan-hang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phieu_chi_tien_mat {
            get {
                object obj = ResourceManager.GetObject("phieu-chi-tien-mat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phieu_kiemtranguyenlieu {
            get {
                object obj = ResourceManager.GetObject("phieu-kiemtranguyenlieu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phieu_kiemtrathanhpham {
            get {
                object obj = ResourceManager.GetObject("phieu-kiemtrathanhpham", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phieu_thu_ngan_hang {
            get {
                object obj = ResourceManager.GetObject("phieu-thu-ngan-hang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Phieu_Thu_Tien_Mat {
            get {
                object obj = ResourceManager.GetObject("Phieu-Thu-Tien-Mat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phieu_yeucaukiemnguyenlieu {
            get {
                object obj = ResourceManager.GetObject("phieu-yeucaukiemnguyenlieu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phieu_yeucaukiemthanhpham {
            get {
                object obj = ResourceManager.GetObject("phieu-yeucaukiemthanhpham", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phieutrakqbenngoai_choQLCL {
            get {
                object obj = ResourceManager.GetObject("phieutrakqbenngoai-choQLCL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phieutrakqphtichtaiPPT {
            get {
                object obj = ResourceManager.GetObject("phieutrakqphtichtaiPPT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phieuyc_phantich {
            get {
                object obj = ResourceManager.GetObject("phieuyc-phantich", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phieuyc_phantich_guingoai {
            get {
                object obj = ResourceManager.GetObject("phieuyc-phantich-guingoai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phongphantich {
            get {
                object obj = ResourceManager.GetObject("phongphantich", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap quanly_chatluong {
            get {
                object obj = ResourceManager.GetObject("quanly-chatluong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap quidinhchatluongnguyenlieu {
            get {
                object obj = ResourceManager.GetObject("quidinhchatluongnguyenlieu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap quidinhchatluongthanhpham {
            get {
                object obj = ResourceManager.GetObject("quidinhchatluongthanhpham", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReportChiPhiVattu {
            get {
                object obj = ResourceManager.GetObject("ReportChiPhiVattu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReportChiPhiVattuKhac {
            get {
                object obj = ResourceManager.GetObject("ReportChiPhiVattuKhac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reportChiTietPhe {
            get {
                object obj = ResourceManager.GetObject("reportChiTietPhe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reportChiTiettaiChe {
            get {
                object obj = ResourceManager.GetObject("reportChiTiettaiChe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReportKQBocxep {
            get {
                object obj = ResourceManager.GetObject("ReportKQBocxep", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReportKQBocxeptonghop {
            get {
                object obj = ResourceManager.GetObject("ReportKQBocxeptonghop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReportKQVanChuyen {
            get {
                object obj = ResourceManager.GetObject("ReportKQVanChuyen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Reportmuahang {
            get {
                object obj = ResourceManager.GetObject("Reportmuahang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reportNhapXuatNL {
            get {
                object obj = ResourceManager.GetObject("reportNhapXuatNL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reportNXthanhpham {
            get {
                object obj = ResourceManager.GetObject("reportNXthanhpham", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReportSLSX {
            get {
                object obj = ResourceManager.GetObject("ReportSLSX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReportSLThanhPham {
            get {
                object obj = ResourceManager.GetObject("ReportSLThanhPham", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReportSoLuongban {
            get {
                object obj = ResourceManager.GetObject("ReportSoLuongban", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReportTonghop {
            get {
                object obj = ResourceManager.GetObject("ReportTonghop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reportTonKho {
            get {
                object obj = ResourceManager.GetObject("reportTonKho", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reportTonKho1 {
            get {
                object obj = ResourceManager.GetObject("reportTonKho1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reportTonkhoPhe {
            get {
                object obj = ResourceManager.GetObject("reportTonkhoPhe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reportTonKhoPremix {
            get {
                object obj = ResourceManager.GetObject("reportTonKhoPremix", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reportTonVattu {
            get {
                object obj = ResourceManager.GetObject("reportTonVattu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReportTonVtuOld {
            get {
                object obj = ResourceManager.GetObject("ReportTonVtuOld", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReportXuatNhap {
            get {
                object obj = ResourceManager.GetObject("ReportXuatNhap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap so_kho_hang {
            get {
                object obj = ResourceManager.GetObject("so-kho-hang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap so_luong_kho_hang {
            get {
                object obj = ResourceManager.GetObject("so luong kho hang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap So_Quy {
            get {
                object obj = ResourceManager.GetObject("So Quy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap so_tien_goi_ngan_hang {
            get {
                object obj = ResourceManager.GetObject("so-tien-goi-ngan-hang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap so_tk_kho {
            get {
                object obj = ResourceManager.GetObject("so-tk-kho", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap so_tong_hop_theo_ngoai_te {
            get {
                object obj = ResourceManager.GetObject("so-tong-hop-theo-ngoai-te", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap so_tong_hop_theo_tai_khoan {
            get {
                object obj = ResourceManager.GetObject("so-tong-hop-theo-tai-khoan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap so_tong_hop_theo_tai_khoan1 {
            get {
                object obj = ResourceManager.GetObject("so-tong-hop-theo-tai-khoan1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap so_tong_hop_theo_yeu_to {
            get {
                object obj = ResourceManager.GetObject("so-tong-hop-theo-yeu-to", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap so_tonghop_theo_doi_tuong {
            get {
                object obj = ResourceManager.GetObject("so-tonghop-theo-doi-tuong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SoCheThuoc {
            get {
                object obj = ResourceManager.GetObject("SoCheThuoc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_BAOCAO {
            get {
                object obj = ResourceManager.GetObject("SX_BAOCAO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_BAOCAO_NGHIEN {
            get {
                object obj = ResourceManager.GetObject("SX_BAOCAO_NGHIEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_BAOCAO_SOCHETHUOC {
            get {
                object obj = ResourceManager.GetObject("SX_BAOCAO_SOCHETHUOC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_BAOCAO_SX_NHAPXUATTON {
            get {
                object obj = ResourceManager.GetObject("SX_BAOCAO_SX_NHAPXUATTON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_BAOCAO_TONGHOP {
            get {
                object obj = ResourceManager.GetObject("SX_BAOCAO_TONGHOP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_DANHMUC {
            get {
                object obj = ResourceManager.GetObject("SX_DANHMUC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_DANHMUC_CONGTHUC {
            get {
                object obj = ResourceManager.GetObject("SX_DANHMUC_CONGTHUC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_DANHMUC_CONGTHUC_NGHIEN {
            get {
                object obj = ResourceManager.GetObject("SX_DANHMUC_CONGTHUC_NGHIEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_DANHMUC_CONGTHUC_THANHPHAM {
            get {
                object obj = ResourceManager.GetObject("SX_DANHMUC_CONGTHUC_THANHPHAM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_DANHMUC_CONGTHUC_TRONTHUOC {
            get {
                object obj = ResourceManager.GetObject("SX_DANHMUC_CONGTHUC_TRONTHUOC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_DANHMUC_NGUYENLIEU {
            get {
                object obj = ResourceManager.GetObject("SX_DANHMUC_NGUYENLIEU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_DANHMUC_NGUYENLIEU_BAOBINGUYENLIEU {
            get {
                object obj = ResourceManager.GetObject("SX_DANHMUC_NGUYENLIEU_BAOBINGUYENLIEU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_DANHMUC_NGUYENLIEU_BAOBITHUOC {
            get {
                object obj = ResourceManager.GetObject("SX_DANHMUC_NGUYENLIEU_BAOBITHUOC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_DANHMUC_THANHPHAM {
            get {
                object obj = ResourceManager.GetObject("SX_DANHMUC_THANHPHAM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_DANHMUC_THANHPHAM_KICHTHUC {
            get {
                object obj = ResourceManager.GetObject("SX_DANHMUC_THANHPHAM_KICHTHUC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_DANHMUC_THANHPHAM_PHANLOAI {
            get {
                object obj = ResourceManager.GetObject("SX_DANHMUC_THANHPHAM_PHANLOAI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_DANHMUC_THANHPHAM_TRONGLUONG {
            get {
                object obj = ResourceManager.GetObject("SX_DANHMUC_THANHPHAM_TRONGLUONG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_KetHoachSanXuat {
            get {
                object obj = ResourceManager.GetObject("SX_KetHoachSanXuat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_SANXUAT {
            get {
                object obj = ResourceManager.GetObject("SX_SANXUAT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_SANXUAT_NGHIEN {
            get {
                object obj = ResourceManager.GetObject("SX_SANXUAT_NGHIEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_SANXUAT_SOCHETHUOC {
            get {
                object obj = ResourceManager.GetObject("SX_SANXUAT_SOCHETHUOC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_SANXUAT_THANHPHAM {
            get {
                object obj = ResourceManager.GetObject("SX_SANXUAT_THANHPHAM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_SANXUAT_XNNGHIEN {
            get {
                object obj = ResourceManager.GetObject("SX_SANXUAT_XNNGHIEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_SANXUAT_XNNGHIEN1 {
            get {
                object obj = ResourceManager.GetObject("SX_SANXUAT_XNNGHIEN1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_SANXUAT_XNSOCHETHUOC {
            get {
                object obj = ResourceManager.GetObject("SX_SANXUAT_XNSOCHETHUOC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_SANXUAT_XNSOCHETHUOC1 {
            get {
                object obj = ResourceManager.GetObject("SX_SANXUAT_XNSOCHETHUOC1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_SANXUAT_XNTHANHPHAM {
            get {
                object obj = ResourceManager.GetObject("SX_SANXUAT_XNTHANHPHAM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_SANXUAT_XNTHANHPHAM1 {
            get {
                object obj = ResourceManager.GetObject("SX_SANXUAT_XNTHANHPHAM1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SX_TONDONGSANXUAT {
            get {
                object obj = ResourceManager.GetObject("SX_TONDONGSANXUAT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SXTongHopNam {
            get {
                object obj = ResourceManager.GetObject("SXTongHopNam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SXTongHopThang {
            get {
                object obj = ResourceManager.GetObject("SXTongHopThang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tai_khoan_ke_toan {
            get {
                object obj = ResourceManager.GetObject("tai-khoan-ke-toan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tai_khoan_kho_hang {
            get {
                object obj = ResourceManager.GetObject("tai-khoan-kho-hang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap taisancodinh {
            get {
                object obj = ResourceManager.GetObject("taisancodinh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap taisancodinh1 {
            get {
                object obj = ResourceManager.GetObject("taisancodinh1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap taisancodinh2 {
            get {
                object obj = ResourceManager.GetObject("taisancodinh2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tang_gia_tsd {
            get {
                object obj = ResourceManager.GetObject("tang-gia-tsd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tansuatkiemtranguyenlieu {
            get {
                object obj = ResourceManager.GetObject("tansuatkiemtranguyenlieu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tansuatkiemtrathanhpham {
            get {
                object obj = ResourceManager.GetObject("tansuatkiemtrathanhpham", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap theo_doi_HD {
            get {
                object obj = ResourceManager.GetObject("theo doi HD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thk_ycngoaichuakq {
            get {
                object obj = ResourceManager.GetObject("thk-ycngoaichuakq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thongke_ketquafantichnglieu {
            get {
                object obj = ResourceManager.GetObject("thongke-ketquafantichnglieu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thongke_ketquafantichnglieu1 {
            get {
                object obj = ResourceManager.GetObject("thongke-ketquafantichnglieu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thongke_ketquafantichTP {
            get {
                object obj = ResourceManager.GetObject("thongke-ketquafantichTP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thongke_ketquafantichTP1 {
            get {
                object obj = ResourceManager.GetObject("thongke-ketquafantichTP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thongke_yckiemnguyenlieu {
            get {
                object obj = ResourceManager.GetObject("thongke-yckiemnguyenlieu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thongke_yckiemnthanhpham {
            get {
                object obj = ResourceManager.GetObject("thongke-yckiemnthanhpham", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thongke_yckiemnthanhphamPPT {
            get {
                object obj = ResourceManager.GetObject("thongke-yckiemnthanhphamPPT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThongKeNLSoChe {
            get {
                object obj = ResourceManager.GetObject("ThongKeNLSoChe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThongKeNLSX {
            get {
                object obj = ResourceManager.GetObject("ThongKeNLSX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tienich {
            get {
                object obj = ResourceManager.GetObject("tienich", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tondong {
            get {
                object obj = ResourceManager.GetObject("tondong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tong_hop_mua_hang {
            get {
                object obj = ResourceManager.GetObject("tong hop mua hang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TonTru {
            get {
                object obj = ResourceManager.GetObject("TonTru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VattuCTNhapXuat {
            get {
                object obj = ResourceManager.GetObject("VattuCTNhapXuat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vontienmat {
            get {
                object obj = ResourceManager.GetObject("vontienmat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xem_phieuyckiemtranglieu {
            get {
                object obj = ResourceManager.GetObject("xem-phieuyckiemtranglieu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xem_phieuyckiemtrathpham {
            get {
                object obj = ResourceManager.GetObject("xem-phieuyckiemtrathpham", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xemphieu_ycktrTP_hngay {
            get {
                object obj = ResourceManager.GetObject("xemphieu-ycktrTP-hngay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xuatsudung {
            get {
                object obj = ResourceManager.GetObject("xuatsudung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
